
services:
  db:
    image: postgres:15-alpine
    container_name: fit4110-db-lab05
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-notifications_db}
    ports:
      - "5432:5432"
    networks:
      - team-internal
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-notifications_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fit4110-rabbitmq-lab05
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - team-internal
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fit4110-api-lab05
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - APP_PORT=8000
      - AUTH_TOKEN=${AUTH_TOKEN:-local-dev-token}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-notifications_db}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - team-internal
      - class-net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: fit4110-worker-lab05
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-notifications_db}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - team-internal
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  team-internal:
    name: team-internal
  class-net:
    external: true

volumes:
  db_data: